Repository valueGa/valueGa_backend, pull requests merged in 2024-06, with the labels that each got.

#5 [FEAT] 모델 생성 #2
  config/config.js
  models/finance_infos.js
  models/index.js
  models/stock.js
  models/template.js
  models/user.js
  models/user_template.js
  models/value_boards.js
  package.json
Labels: feat

#13 [FEAT] db에 엑셀=>바이너리 저장 #11 [Type] #11
  models/user_template.js
  routes/upload.js
  server.js
Labels: feat

#16 [FEAT] DB에서 엑셀 불러오기 #11
  routes/upload.js
  routes/uploads/a.xlsx
  routes/uploads/restored_a.xlsx
Labels: feat

#19 [FEAT] 회원가입, 로그인, 로그아웃 기능 구현 #17
  models/index.js
  models/user.js
  models/user_template.js
  package-lock.json
  package.json
  routes/auth.js
  routes/upload.js
  server.js
Labels: feat

#25 [FEAT] 임시저장, 저장 api 개발 #20
  routes/upload.js
Labels: feat

#32 [FIX] API 엔드포인트 리팩터링 및 swagger관련 오류 수정 #31
  .github/workflows/deploy-to-ec2.yml
  models/finance_infos.js
  models/index.js
  routes/auth.js
  routes/valuation.js
  server.js
Labels: fix, refactor

#34 [FIX] 모델 수정 #33
  models/consensus.js
  models/index.js
  models/template.js
  models/user_template_temporary.js
  models/valuation.js
  models/value_boards.js
Labels: fix

#38 [FEAT] 벨류에이션 생성시 3개년 데이터 가져오는 API 구현 #26
  routes/valuation.js
Labels: feat

#42 [FEAT] 컨센서스 조회 API 개발
  routes/consensus.js
  server.js
Labels: feat

#41 [FEAT] 저장, 임시저장 api 수정
  .gitignore
  models/valuation.js
  routes/uploads/a.xlsx
  routes/uploads/restored_a.xlsx
  routes/valuation.js
  server.js
Labels: feat

#46 [FEAT] 템플릿화 API, DB저장 기능 구현 #40
  routes/template.js
  server.js
Labels: feat

#48 [FEAT] template id로 조회하는 API 작성 #47
  routes/template.js
Labels: feat

#52 [FIX] api 요청 경로 수정, 템플릿 저장 경로 수정 #26
  routes/template.js
  routes/valuation.js
Labels: fix

#68 [FEAT] 변경된 엑셀 라이브러리에 따라 템플릿화 API 변경 #61
  routes/template.js
Labels: fix

#69 [FEAT]: 종합 컨센서스 API 수정
  routes/consensus.js
Labels: feat

#71 [FIX] 엑셀 라이브러리 수정에 따라 벨류에이션 조회 api 수정 #61
  routes/valuation.js
  service/generateInitYears.js
Labels: feat, fix

#77 [FEAT]: 개별 컨센서스 재무 데이터 추가 #73
  routes/consensus.js
  server.js
Labels: feat

#82 [FEAT] DEVELOP 기능 MAIN 브랜치에 반영
  .github/workflows/deploy-to-ec2.yml
  .gitignore
  config/db.config.js
  data_preprocessing/csv_to_pg_migration.py
  data_preprocessing/dart_finanical_data_parser.py
  data_preprocessing/dart_sales_infos_parser.py
  data_preprocessing/dart_stock_infos_parser.py
  data_preprocessing/make_csv_file.py
  data_preprocessing/simulate.sh
  models/consensus.js
  models/finance_infos.js
  models/index.js
  models/stock.js
  models/template.js
  models/user.js
  models/valuation.js
  package-lock.json
  package.json
  routes/auth.js
  routes/consensus.js
  routes/search.js
  routes/template.js
  routes/user.js
  routes/valuation.js
  server.js
  service/generateInitYears.js
  service/getAccessToken.js
  service/getCurrentStockPrice.js
  service/getDailyChart.js
  service/getEV_EBITDA.js
  service/getFinance.js
  service/getInfos.js
  service/getRatio.js
  service/mergeData.js
  swagger/swagger.js
Labels: feat

#85 [FIX] 중복 검색어 응답, 검색어 대문자 변환 수정#83
  routes/search.js
Labels: feat, fix

#89 [REFACTOR] openAPI 로직 리팩토링 /#88
  routes/consensus.js
  routes/valuation.js
  service/fetchData.js
Labels: refactor

#91 [FIX]: 데이터 전처리 후 삽입 로직 수정 #90
  data_preprocessing/csv_to_pg_migration.py
  data_preprocessing/insert_stocks.py
Labels: fix

#92 [FIX]: func undefine 오류 수정 #88
  service/fetchData.js
Labels: fix

#94 [REFACTOR]/#93
  routes/template.js
  routes/valuation.js
Labels: refactor

#95 [FEAT] DEVELOP 기능 MAIN 병합
  data_preprocessing/csv_to_pg_migration.py
  data_preprocessing/insert_stocks.py
  routes/consensus.js
  routes/search.js
  routes/template.js
  routes/valuation.js
  service/fetchData.js
Labels: feat

#98 [FIX]: 개별 컨센서스 API 수정
  routes/consensus.js
Labels: fix

#99 [FEAT] DEVELOP 기능 MAIN 병합
  routes/consensus.js
Labels: feat
